
apiVersion: v1
kind: Pod
metadata:
  name: video-initialise
apiVersion: v1
kind: Pod
metadata:
  name: test-local-vol-1
  labels:
    name: test-local-vol-1
spec:
  containers:
  - name: app
    image: vasu1711/bash-curl:latest  
    command: ['sh', '-c', 'sleep 3600']


