
apiVersion: v1
kind: Pod
metadata:
  name: test3-deployment-2-initialise
spec:
  containers:
  - name: test3-initialise
    image: busybox
    command:  ["/bin/sh", "-c", "ls && sleep 3600"]
    volumeMounts:
    - mountPath: /test
      name: test3-local-pv
      readOnly: true
  volumes:
  - name: test3-local-pv
    hostPath:
      path:  /pv/deployment2
      type: DirectoryOrCreate 

--- 


kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test3-deployment-2-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: test3-deployment-2-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: test3-deployment-2-storage
  local:
    path: /pv/deployment2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-multiserver-server-0

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test3-deployment-2-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: test3-deployment-2-storage
  resources:
    requests:
      storage: 1Gi 

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3-deployment-2
  labels:
    app: test3-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test3-deployment-2
  template:
    metadata:
      labels:
        app: test3-deployment-2
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-multiserver-server-0
      volumes:
        - name: test3-deployment-2-local-persistent-storage
          persistentVolumeClaim:
            claimName: test3-deployment-2-pvc
        - name: test3-deployment-2-local-pv
          hostPath:
            path: /pv/deployment2
            type: DirectoryOrCreate 
      initContainers:
      - name: test3-deployment-2-init
        image: arearnest7/video-recog-partial-wob:latest
        volumeMounts:
          - name: test3-deployment-2-local-persistent-storage
            mountPath: /mnt
        securityContext:
          runAsUser: 0  
        command: ["sh", "-c", "cp -r /workspace/* /mnt/"]
      containers:
      - name: test3-deployment-2
        image: arearnest7/video-recog-partial-wob:latest
        volumeMounts:
          - name: test3-deployment-2-local-persistent-storage
            mountPath: /mnt
        securityContext:
          runAsUser: 0  
        ports:
        - containerPort: 8080
